/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskForm: typeof import('./components/forms/TaskForm.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TheAppBar: typeof import('./components/layout/TheAppBar.vue')['default']
    TheHeader: typeof import('./components/layout/TheHeader.vue')['default']
    TheSidebar: typeof import('./components/layout/TheSidebar.vue')['default']
    UpdateTaskDialog: typeof import('./components/dialog/UpdateTaskDialog.vue')['default']
  }
}
